### ISSUE TITLE
off()ing within callback causes another callback to be skipped

### ISSUE THREAD

**Issue by RalphCorderoy** [Ben-Honeywill/ezvent#1]
Hi, Not a user of this code, but I did read https://atech.blog/atech/creating-a-simple-custom-event-system-in-javascript and discussed it briefly on Dorset LUG's IRC, 2017-08-09 10:45:54:

> > I don't know Javascript so could be wrong, but forEach-ing over a [] that can have items deleted with splice() looks dodgy.  If fire() has three things to callback and the first off()s itself then I think the second won't fire because the third will be in its place.
>
> a = [1, 2, 3]; a.forEach(function(e){ a.splice(0, 1); console.log(e) })
> Indeed skips 2.

**Comment by Ben-Honeywill** [comment]
Hi Ralph,

Thanks for your help! For sure an oversight on my part :-1:

I just [pushed out a fix](https://github.com/Ben-Honeywill/ezvent/commit/53b2d4d9004d5c38fa642459b2e4a21156544d29) that I believe fixes the problem you were talking about. I'll get the blog post updated soon too.

Thanks again! Let me know if you spot anything else :smile:
